[build]
builder = "NIXPACKS"
nixpacksPkgs = ["tesseract"]

[build.nixpacks.plan]
providers = ["python"]

[deploy]
start = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

root = "."

[build.env]
PYTHON_VERSION = "3.11"