[build]
builder = "NIXPACKS"

[build.nixpacks]
packages = [
  "tesseract",
  "zbar",
  "git",
  "libstdc++",
  "libgcc",
  "libgl1",
  "libglib2.0",
]

[build.env]
PYTHON_VERSION = "3.11"

[deploy]
start = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
root = "."